### ISSUE TITLE
Missing doc of version restriction

### ISSUE THREAD

**Issue by lipelix** [aaronstillwell/terraform-provider-dokku#12]
Hi, I spend some time trying to make provider work to deploy app on digital ocean droplet. Unfortunately there is running older version of dokku:

```Error: This provider has not been tested against Dokku version 0.21.4. Tested version range: >=0.24.0 <0.29.0```

I suggest to mention this **version restriction** somewhere in readme.

**Comment by aaronstillwell** [comment]
Thanks for the contribution @lipelix. Indeed this seems like a good addition to the readme, I'll follow up in due course.

You can override this check with the `fail_on_untested_version` attribute like so:

```
provider "dokku" {
  ssh_host = "dokku.me"
  ssh_user = "dokku"
  ssh_port = 8022
  ssh_cert = "/home/user/.ssh/dokku-cert"
  
  # Tell the provider not to fail if a dokku version is detected that hasn't
  # been tested against the current version of the provider.
  fail_on_untested_version = true
}
```

it'd just be up to you to ensure that the provider isn't going to try and run any commands that were introduced since the version of dokku you're using, or you might hit some errors.
